server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://192.168.100.101:3306/oauth2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/template/
    suffix: .html
    cache: false
